# Generated by Django 4.0.8 on 2024-03-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='classes',
            field=models.TextField(default='[]'),
        ),
    ]
