# Generated by Django 4.0.8 on 2024-03-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_year_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='classes',
            field=models.TextField(default=''),
        ),
    ]
