# Generated by Django 5.0.1 on 2024-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_year_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='class_obj',
        ),
        migrations.AddField(
            model_name='student',
            name='massar',
            field=models.CharField(default='P', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='members',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='year',
            name='classes',
            field=models.TextField(max_length=10000, verbose_name='Classes:'),
        ),
    ]
