# Generated by Django 5.0.1 on 2024-03-08 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_student_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='name',
            new_name='year',
        ),
        migrations.AddField(
            model_name='year',
            name='class_types',
            field=models.CharField(choices=[('APIC', 'International'), ('AGSE', 'General')], default='APIC', max_length=13, verbose_name='Class Type:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='year',
            name='classes',
            field=models.TextField(max_length=10000, unique=True, verbose_name='Classes:'),
        ),
    ]
