# Generated by Django 5.0.1 on 2024-03-09 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_name_year_year_class_type_year_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='type',
        ),
        migrations.RemoveField(
            model_name='year',
            name='classes',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APIC', 'International'), ('AGSE', 'General')], max_length=50)),
                ('classes', models.ManyToManyField(to='main_app.class')),
            ],
        ),
        migrations.AlterField(
            model_name='year',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.classtype'),
        ),
    ]
