# Generated by Django 5.0.1 on 2024-03-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_class_members_remove_student_class_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
