# Generated by Django 5.0.1 on 2024-03-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_classtype_name_alter_year_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtype',
            name='year',
        ),
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('APIC', 'APIC'), ('AGSE', 'AGSE')], default='AGSE', max_length=10),
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.CharField(choices=[('year1', '1'), ('year2', '2'), ('year3', '3')], default='1', max_length=10),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.DeleteModel(
            name='ClassType',
        ),
    ]
