# Generated by Django 5.0.1 on 2024-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_classtype_year_alter_class_type_class_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3')], default='1', max_length=10),
        ),
    ]
