# Generated by Django 5.0.1 on 2024-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_class_name_alter_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3')], default=1, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('year', 'type', 'name')},
        ),
    ]
