# Generated by Django 5.0.1 on 2024-03-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_class_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('year', 'type', 'name')},
        ),
    ]
