# Generated by Django 5.0.1 on 2024-03-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_class_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('AGSE', 'AGSE'), ('APIC', 'APIC')], default='AGSE', max_length=10),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_table', models.CharField(max_length=120)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.class')),
            ],
        ),
    ]
