# Generated by Django 5.0.1 on 2024-03-20 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_class_type_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='course',
        ),
        migrations.AddField(
            model_name='staff',
            name='class_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.class'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.class', verbose_name='Class:'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_table',
            field=models.FileField(upload_to='', verbose_name='Time Table:'),
        ),
    ]
