# Generated by Django 5.0.1 on 2024-03-24 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_subject_course_alter_staff_class_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.class'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.class', verbose_name='Class:'),
        ),
    ]
