# Generated by Django 5.0.1 on 2024-03-24 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_timetable_staff_alter_student_class_obj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='staff',
        ),
    ]
