# Generated by Django 5.0.1 on 2024-03-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_timetable_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='class_obj',
        ),
        migrations.AddField(
            model_name='staff',
            name='class_obj',
            field=models.ManyToManyField(blank=True, to='main_app.class', verbose_name='Classes'),
        ),
    ]
