# Generated by Django 5.0.1 on 2024-03-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_staff_class_obj_staff_class_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='class_obj',
            field=models.ManyToManyField(blank=True, to='main_app.class', verbose_name='Classes:'),
        ),
    ]
