# Generated by Django 5.0.1 on 2024-04-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_class_name_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Profile picture: '),
        ),
    ]
